### ISSUE TITLE
No eplusout.csv in the output file, thus cannot use monitoring function

### ISSUE THREAD

**Issue by DDDOH** [IBM/rl-testbed-for-energyplus#105]
Hi, I run the simulation till the step function returns DONE=True, and got a list of outputs but without eplusout.csv.
<img width="555" alt="image" src="https://user-images.githubusercontent.com/25512742/177042003-f8c8707c-0000-4ee7-9863-3c82a091dc81.png">

The environment is the manually installed energyplus 9.5.0 on MacOS with an M1 chip. But when I run exactly the same code in a Linux docker the eplusout.csv shows.

Is it possible to fix this issue by working around the code? Or do I have to switch to docker instead?

**Comment by antoine-galataud** [comment]
Hi @DDDOH, there should be no difference in code executed inside and outside a container: EnergyPlus is called with `-r` which invokes transformation of `.eso` to the expected `.csv`. It happens at the very end of the execution of the simulation (hence end of episode) and it’s tackled by a different binary (`ReadVarsESO`). Could you try to rerun for 2 complete episodes and check the output folder of the first one? If `eplusout.csv` is still missing please share the logs of the execution.

**Comment by DDDOH** [comment]
Thanks for your reply. I tried run the code in the docker environment and the issue is resolved. The missing .csv may related to the MacOS M1 version Energyplus.
