### ISSUE TITLE
Fail to patch same as #56

### ISSUE THREAD

**Issue by Arannnn** [IBM/rl-testbed-for-energyplus#108]
<img width="651" alt="微信截图_20220721203943" src="https://user-images.githubusercontent.com/92990088/180216282-d8d015d7-1442-43a5-964b-9436d9d6000e.png">

**Comment by antoine-galataud** [comment]
Hi @Arannnn. The patch you’re trying to apply is to the one that fixes EnergyPlus 9.1 installer, and is a only necessary for version 9.1.
If you’re using this version, make sure you apply the patch where the installer have been downloaded (not where this repo’s sources are located, and not where EnergyPlus sources are located either).

**Comment by Arannnn** [comment]
Thank you for your help. Because English is my second language, I can't express my gratitude

**Comment by antoine-galataud** [comment]
Glad it helped!
