### ISSUE TITLE
ExtCtrlObs function

### ISSUE THREAD

**Issue by khoderj** [IBM/rl-testbed-for-energyplus#12]
The built-in function ExtCtrlObs as described in the paper represents the state vector and expects two parameters; the index and its corresponding value. However, the two models in the repository (other than the baseline model) don't always abide by the function definition and they call it as follows:
          - SET tmp_val1 = @ExtCtrlObs 0;
Thus, the following error is raised:
           - FATAL:EMS Runtime Language: did not find valid input for built-in function =@EXTCTRLOBS 0
Thank you in advance for your help.

Best Regards,
Khoder Jneid

**Comment by khoderj** [comment]
Could someone please provide me with some information on how the problem could be fixed?

Regards,
Khoder Jneid

**Comment by takaomoriyama** [comment]
The error message says the new command "@EXTCTRLOBJS" is not registered to EnergyPlus you are running. Please check the followings.
Confirm if patch to EnergyPlus is successfully applied. How to patch is described in the README.md as follows:
```
$ patch -p1 < ../rl-testbed-for-energyplus/EnergyPlus/RL-patch-for-EnergyPlus-8-8-0.patch
```
I'd recommend the following command and see nothing is output. If *.rej file is shown,  there is some error in patching EnergyPlus source code.
```
find . -name "*.rej"
```

**Comment by khoderj** [comment]
Executing the command (find ...) didn't output anything but the problem was solved when patching is performed again.
Much appreciated.

**Comment by takaomoriyama** [comment]
Additional note:

If you are using EnergyPlus v9.1.0, use the following command instead.
```
$ patch -p1 < ../rl-testbed-for-energyplus/EnergyPlus/RL-patch-for-EnergyPlus-9-1-0.patch
```
