### ISSUE TITLE
Error count

### ISSUE THREAD

**Issue by khoderj** [IBM/rl-testbed-for-energyplus#13]
When executing the command: time python3 -m baselines_energyplus.trpo_mpi.run_energyplus --num-timesteps 100, I am having the following error:
EnergyPlusEnv: Severe error(s) occurred. Error count: -1
EnergyPlusEnv: Check contents of .../eplog/openai-2019-01-17-17-15-39-178654/output/episode-00000001/eplusout.err

And when checking the error log file, no error found:
Program Version,EnergyPlus, Version 8.8.0-7c3bbe4830, YMD=2019.01.17 17:25,IDD_Version 8.8.0
   ************* Beginning Zone Sizing Calculations
   ** Warning ** Weather file location will be used rather than entered (IDF) Location object.
   **   ~~~   ** ..Location object=CHICAGO_IL_USA TMY2-94846
   **   ~~~   ** ..Weather File Location=San Francisco Intl Ap CA USA TMY3 WMO#=724940
   **   ~~~   ** ..due to location differences, Latitude difference=[4.16] degrees, Longitude difference=[34.65] degrees.
   **   ~~~   ** ..Time Zone difference=[2.0] hour(s), Elevation difference=[98.95] percent, [188.00] meters.

Moreover, I checked the new values of the parameters modified by the patch file (TempTol, MaxIte) and they are modified as mentioned in the paper.
Thank you in advance for your permanent assistance.

**Comment by takaomoriyama** [comment]
@khoderj 
Severe error count of -1 does not mean occurence of severe error, but something other situation might have occurred. There are two reasons for error count of -1:
- The error file "eplusout.err" was not found.
- The error file did not contain a line containing "************* EnergyPlus Completed Successfully". 

In your case, you have the error file. So please check the second condition.
Any error file should be ending with the lines like following:
```
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 4 Warning; 0 Severe Errors.
   ************* EnergyPlus Completed Successfully-- 41669 Warning; 971 Severe Errors; Elapsed Time=00hr 00min 30.93sec
```

**Comment by myndtrust** [comment]
@khoderj

I am having a similar issue, but the err file I get is is empty. How did you fix this issue?

My err file
`Program Version,EnergyPlus, Version 8.8.0-7c3bbe4830, YMD=2019.05.01 20:21,IDD_Version 8.8.0
   ************* Beginning Zone Sizing Calculations`

**Comment by khoderj** [comment]
I couldn't find the reason behind the problem. However, I got the problem fixed when running on a different version of Ubuntu (16.04).

**Comment by xiaonanchong** [comment]
@khoderj 
I have exactly the same issue, I wonder how did you solve the problem?
![1](https://user-images.githubusercontent.com/20331748/57147815-517ff700-6dc0-11e9-8157-4b3b7ce67497.PNG)

thank you in advance.
