### ISSUE TITLE
syntax problem  

### ISSUE THREAD

**Issue by xiaonanchong** [IBM/rl-testbed-for-energyplus#18]
Hi, I am running the codes without any change on UBUNTU16.04. however i encountered the following error. I wonder if anyone have the same issue and how to fix this?

![Capture](https://user-images.githubusercontent.com/20331748/57125430-58d3e000-6d81-11e9-9cf7-143463f89ddc.PNG)

I tried to change code in rl-testbed-for-energyplus/baselines_energyplus/trpo_mpi, change codes to:
![1](https://user-images.githubusercontent.com/20331748/57128322-f7187380-6d8a-11e9-941b-386552142ab3.PNG)

then come up another syntax problem that I don't know how to fix:
![2](https://user-images.githubusercontent.com/20331748/57128468-6726f980-6d8b-11e9-8be0-bbd67cde7b38.PNG)

**Comment by khoderj** [comment]
This is posted in one of the closed issues: "direct crashing". It is related to the version of the baselines. Read that issue and then you will get the solution.
