### ISSUE TITLE
file path configuration

### ISSUE THREAD

**Issue by xiaonanchong** [IBM/rl-testbed-for-energyplus#19]
even though I have already change the SOMEWHERE in bashrc, however I still have this issue:
**FileNotFoundError: [Errno 2] No such file or directory: 'SOMEWHERE/rl-testbed-for-energyplus/EnergyPlus/Model/2ZoneDataCenterHVAC_wEconomizer_Temp_Fan.idf'
EnergyPlusEnv: Severe error(s) occurred. Error count: -1**
![捕获](https://user-images.githubusercontent.com/20331748/57548479-f4a0b580-7358-11e9-99bc-82ec83e3e8d7.PNG)

can someone help me?

**Comment by myndtrust** [comment]
Have you restarted you workstation or ran source ~/.bashrc.
.bashrc needs to restart or be re-instantiated for the system variable to be recognized.
