### ISSUE TITLE
Problem caused by shorter timestep

### ISSUE THREAD

**Issue by OnedgeLee** [IBM/rl-testbed-for-energyplus#25]
Energyplus goes shorter timestep if zone temperature timestep difference is bigger than 0.3C.
When I receive minutes from Energyplus environment through named pipe, (SET tmp_val1 = @ExtCtrlObs 10 Minute,) I could find shorter timestep comes after normal timestep.
(example, 0:15:00 -> 0:30:00 -> 0:17:00 -> 0:20:00 -> 0:24:00 -> 0:27:00 -> 0:30:00)
AfterPredictorAfterHVACManagers EMS calling point calls EMS program every timesteps, even shorter timesteps.
Rollout sequence goes wrong because of this shorter timesteps.

Rollout should be in sequence 0:15:00 -> 0:30:00 -> 0:45:00 -> 1:00:00 ...
but goes under 0:15:00 -> 0:30:00 -> 0:17:00 -> 0:20:00 ...

Shorter timesteps should be ignored, do actions cloned from normal timesteps,
and shoud be omitted from rollout sequence I think.

**Comment by antoine-galataud** [comment]
Hi @OnedgeLee. 
I think your issue is the same as the one I reported in https://github.com/IBM/rl-testbed-for-energyplus/issues/9
Basically, EnergyPlus has system timesteps that are not meant to be used and should be skipped during rollout or trajectory sampling.

**Comment by OnedgeLee** [comment]
> Hi @OnedgeLee.
> I think your issue is the same as the one I reported in #9
> Basically, EnergyPlus has system timesteps that are not meant to be used and should be skipped during rollout or trajectory sampling.

Thank you, you are right.
