### ISSUE TITLE
How is the baseline created in the paper?

### ISSUE THREAD

**Issue by abhishm** [IBM/rl-testbed-for-energyplus#4]

**Comment by takaomoriyama** [comment]
I just used 2ZoneDataCenterHVAC_wEconomizer.idf file included in EnergyPlus distribution with following changes:
- Change simulation period from 14 days to 365 days.

**Comment by abhishm** [comment]
Thank you!

**Comment by abhishm** [comment]
When I created the baseline results, I saw the same power consumption but I saw different rewards. In particular, I obtained the following average rewards:
CA:    0.617175
CO:   0.487033
FL:    0.292638
IL:     0.546689
VA:   0.513958

I used [compute_reward_center23_5_gaussian1_0_trapezoid0_1_pue0_0(raw_state)](        return self.compute_reward_center23_5_gaussian1_0_trapezoid0_1_pue0_0(raw_state)) for computing the reward.

**Comment by takaomoriyama** [comment]
@abhishm I regret to say that I mistakenly used the reward value computed by https://github.com/IBM/rl-testbed-for-energyplus/blob/cba31bd9ab608fd13b74b4054149539d71a64b5f/gym_energyplus/envs/energyplus_model_2ZoneDataCenterHVAC_wEconomizer.py#L113 instead of https://github.com/IBM/rl-testbed-for-energyplus/blob/cba31bd9ab608fd13b74b4054149539d71a64b5f/gym_energyplus/envs/energyplus_model_2ZoneDataCenterHVAC_wEconomizer.py#L101 in the Table 1 of the paper. Thank you for pointing it out. I believe it does not affect to any other portion of the experiment.

To help execute baseline mode, I added ```gym_energyplus/envs/energyplus_model_2ZoneDataCenterHVAC_wEconomizer.py``` so that we can run baseline with ```python3 -m baselines_energyplus.trpo_mpi.run_energyplus --num-timesteps 1```. Note that since ```2ZoneDataCenterHVAC_wEconomizer-baseline.idf``` does not communicate with DRL agent, we need to wait for a while (20min.) until timeout occur. You can modify the timeout period here: https://github.com/IBM/rl-testbed-for-energyplus/blob/cba31bd9ab608fd13b74b4054149539d71a64b5f/gym_energyplus/envs/pipe_io.py#L53

**Comment by takaomoriyama** [comment]
Closing this issue since I think the issue has been resolved.

**Comment by biemann** [comment]
Hi, I think that the current version of the file does not give the results that are reported in the paper (the east zone has higher temperatures than desired). I used EnergyPlus version 9.2.

I had to modify the file `2ZoneDataCenterHVAC_wEconomizer-baseline.idf` (l. 2984)
```
 ElectricEquipment:ITE:AirCooled,
    EastDataCenter_Equip,    !- Name
    East Zone,               !- Zone Name
    !FlowControlWithApproachTemperatures,  !- Air Flow Calculation Method
    FlowFromSystem,            ! New Air Flow Calculation Method
```
where I changed the air flow calculation method. With this I obtained the same results than in the paper. Was this the desired behaviour?

**Comment by yashviagrawal** [comment]
> Closing this issue since I think the issue has been resolved.
@takaomoriyama @abhishm @biemann 

Hello, I have to manually run the contents of the bashrc file whenever I want to execute the code in the terminal. So, when I wanted the model to run for baselines (non rl model), so in the last part if the bashrc file, where is says "Model file. Uncomment one.", it only gives an option for '2ZoneDataCenterHVAC_wEconomizer_Temp.idf' and '2ZoneDataCenterHVAC_wEconomizer_Temp_Fan.idf', it doesn't give an option for '2ZoneDataCenterHVAC_wEconomizer-baseline.idf', so I run that this time, and then it shows this new command after that which I don't know the meaning for. 

I am attaching ss. 
<img width="568" alt="Screenshot 2022-02-14 at 14 56 53" src="https://user-images.githubusercontent.com/74981992/153837239-51e49e41-f789-4e45-b876-94aa063d15b3.png">

Please help me out, if I'm wrong please point me in the right direction.

**Comment by biemann** [comment]
Maybe the code does not stop when using the baseline, but the results should be logged into the log folder, no?

**Comment by biemann** [comment]
But if you are using a baseline controller, you are not training anything, so there is no need to save a model. It is a non-RL controller that aims to maintain the temperature as closely as possible to the setpoint and sets the cooling setpoints of the different components, relying on solving thermodynamical equations (as far as I understand, not expert with EnergyPlus).  This controller is excellent at keeping temperatures in the desired comfort range, but typically uses more energy than we would like.

**Comment by yashviagrawal** [comment]
@biemann OH okay, so I should just quit the code when I reach my desried number of episodes, right?
I had one more doubt, if I wanted to compare the result graph that comes after running the RL model with another result graph, would the graph for baselines be appropriate for comparing to know whether power consumption is minimised using the RL model or not?
