### ISSUE TITLE
HOW TO SOLVE THIS ERROR "fatar error : CommandLineInterface.hh : No such file or a directory"

### ISSUE THREAD

**Issue by minjeong-sim** [IBM/rl-testbed-for-energyplus#43]
![image](https://user-images.githubusercontent.com/71823444/94136045-5060d580-fe9f-11ea-91cf-99b27609efaa.png)
GCC version is 7.5
ubuntu 16.04
make version is 4.1
cmake version is 3.18.2

When I insert the DCMAKE_INSTALL_PREFIX=/usr/local/EnergyPlus-8-8-0 /..
![DCMAKE_INSTALL_PREFIX](https://user-images.githubusercontent.com/71823444/94136198-8900af00-fe9f-11ea-8168-d7401aa900cb.PNG)

And I have this error 
"fatar error : CommandLineInterface.hh : No such file or a directory
![make -j4](https://user-images.githubusercontent.com/71823444/94136279-ab92c800-fe9f-11ea-9d1d-83df57dcff3d.PNG)

How cam i solve it??

**Comment by antoine-galataud** [comment]
Hi @minjeong-sim 

I think your problem is you're on an incorrect branch in your git clone of EnergyPlus. Can you try `git checkout v8.8.0` and re-test?

**Comment by minjeong-sim** [comment]
> Hi @minjeong-sim
> 
> I think your problem is you're on an incorrect branch in your git clone of EnergyPlus. Can you try `git checkout v8.8.0` and re-test?

Thank you for answer @antoine-galataud 
I got this message.
![image](https://user-images.githubusercontent.com/71823444/94276137-cf7b0a00-ff82-11ea-810f-6ae4696bc8ee.png)

and I don't know what to do next.

**Comment by antoine-galataud** [comment]
@minjeong-sim you can simply discard these changes using `git checkout .`
