### ISSUE TITLE
Any plan for dockerfile/docker image?

### ISSUE THREAD

**Issue by Learner0x5a** [IBM/rl-testbed-for-energyplus#66]
Setting up the environment seems a bit complex, it would be very convenient if there's a dockerfile or docker image.
Any plans?

**Comment by antoine-galataud** [comment]
Hi @Learner0x5a 
There is one. See https://github.com/IBM/rl-testbed-for-energyplus/blob/0854a24ca94e6647369a98b1cf5e0eaa68fbd4d5/docker/README.md

Feel free to report any issue with it!

**Comment by Learner0x5a** [comment]
Oops, I missed that. Thanks a lot!
