### ISSUE TITLE
Where is the Model saved?

### ISSUE THREAD

**Issue by yashviagrawal** [IBM/rl-testbed-for-energyplus#71]
Hello, after training where is the model saved, and in which form is it saved (like a q-table or what), and with what extension is the model saved, please help

**Comment by antoine-galataud** [comment]
Hi @yashviagrawal !
By default the learned policy isn’t saved. You can modify the code to support this. Here is an exemple (edit of `baselines_energyplus/trpo_mpi/run_energyplus.py`):

```python
policy = trpo_mpi.learn(
                   env=env,
                   network=mlp(num_hidden=32, num_layers=2),
                   total_timesteps=num_timesteps,
                   #timesteps_per_batch=1*1024, max_kl=0.01, cg_iters=10, cg_damping=0.1,
                   timesteps_per_batch=16*1024, max_kl=0.01, cg_iters=10, cg_damping=0.1,
                   gamma=0.99, lam=0.98, vf_iters=5, vf_stepsize=1e-3)

policy.save(save_path="/path/to/model")
```

see openai baselines code and documentation to learn more (like how to reload a saved model).

**Comment by yashviagrawal** [comment]
Hello @antoine-galataud 
Thank you ao much for your help in saving the model. The issue with the project is that I am unable to figure out in which python file is the number of episodes specified. Without knowing that, the code runs for an endless number of episodes and we have to stop our training mid way, and that in turn doesn't save any model, even after modifying the code you gave above. 
If you could please help with finding the specified number of episodes, I'd be very grateful!

**Comment by antoine-galataud** [comment]
@yashviagrawal I'm afraid there is no way to train for a number of episodes. Only for a number of timesteps. For this you can pass `--num-timesteps 100000` as a command line argument when starting your training

**Comment by yashviagrawal** [comment]
@antoine-galataud Thank you so much for your help!

**Comment by yashviagrawal** [comment]
@antoine-galataud @takaomoriyama 
Hello, do you know how I can load the saved model in this code, and then re-train it?
I trained it for 2000 epochs and saved it, and I haven't seen any improvement or changes in the results, so do you know how I could change that and improve it?

**Comment by yashviagrawal** [comment]
@antoine-galataud @takaomoriyama
Hello, do you know how I can load the saved model in this code, and then re-train it?
I trained it for 2000 epochs and saved it, and I haven't seen any improvement or changes in the results, so do you know how I could change that and improve it?

You had suggested that I see OpenAI baselines code and documentation to know how load the saved model but I haven't been able to find the documentation, so if you could help with that, I'd have something to go on with.

**Comment by antoine-galataud** [comment]
Hi @yashviagrawal,
OpenAI TRPO implementation accepts a `load_path` argument on the `learn` method.

See: https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/trpo_mpi/trpo_mpi.py#L89

So you should be able to do something like:

```python

model_path = "/path/to/model"

# 1st training, from scratch
policy = trpo_mpi.learn(
                   env=env,
                   network=mlp(num_hidden=32, num_layers=2),
                   total_timesteps=num_timesteps,
                   timesteps_per_batch=16*1024, max_kl=0.01, cg_iters=10, cg_damping=0.1,
                   gamma=0.99, lam=0.98, vf_iters=5, vf_stepsize=1e-3)

# save trained policy
policy.save(save_path=model_path)

# 2nd training, from reloaded model
policy = trpo_mpi.learn(
                   env=env,
                   network=mlp(num_hidden=32, num_layers=2),
                   total_timesteps=num_timesteps,
                   timesteps_per_batch=16*1024, max_kl=0.01, cg_iters=10, cg_damping=0.1,
                   gamma=0.99, lam=0.98, vf_iters=5, vf_stepsize=1e-3,
                   load_path=model_path  # reloads the model
         )
```

**Comment by yashviagrawal** [comment]
@antoine-galataud @takaomoriyama Hello
I ran the model for many episodes, saved it and ran it, but it didn't learn using TRPO method. So, I shifted to PPO method, and ran the model, saved it and loaded it and ran it again, and yet the model isn't learning. The reward mean came down from -2 lakhs to -20,000 but now it isn't learning at all. 
Any suggestions on what should I do?

**Comment by antoine-galataud** [comment]
@yashviagrawal I'm closing this issue since the main question was answered and you already opened #84 for the rest.
