### ISSUE TITLE
have a problem from downloading ep launch 9.5 in wsl(18.02) by docker. cuz cannot download some requirements.txt

### ISSUE THREAD

**Issue by Paopasatiht** [IBM/rl-testbed-for-energyplus#81]
numpy -> 1.21.0 is not work
scipy 1.8.0

what i did:
- download wsl & docker & conda & python

problem
- cannot run from `docker build . -f docker/Dockerfile -t rl-testbed-for-energyplus`

**Comment by antoine-galataud** [comment]
Hi @Paopasatiht,
Thank you for reporting this issue. Can you share the error trace you get when you use `docker build`?

**Comment by Paopasatiht** [comment]
![image](https://user-images.githubusercontent.com/58716875/159629148-84bf78a1-a54c-495e-951d-9cde13ac60d1.png)
this is the picture

**Comment by Paopasatiht** [comment]
![image](https://user-images.githubusercontent.com/58716875/159783660-7f9cf85b-5140-421b-911a-7d279634df73.png)
I config the Dockerfile like this to make it become version 9.5 link is down below but I still find the error like this:
https://github.com/NREL/EnergyPlus/releases/download/v9.5.0/EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu20.04-x86_64.sh

this is my error.
![image](https://user-images.githubusercontent.com/58716875/159783984-e72221bd-245a-4cd1-b929-f0ea23f5a53f.png)

**Comment by antoine-galataud** [comment]
@Paopasatiht I've worked on a new version of the Dockerfile that uses EnergyPlus 9.5 and Ubuntu 20.04. I've been able to successfully build it and run an experiment in a container.

Please give it a try:

```shell
cd rl-testbed-for-energyplus
git pull
docker build . -f docker/Dockerfile -t rl-testbed-for-energyplus
```

**Comment by Paopasatiht** [comment]
now i found this error after use your code:
![image](https://user-images.githubusercontent.com/58716875/160235588-ee899838-db5c-451d-ab8a-dea850328205.png)

**Comment by antoine-galataud** [comment]
@Paopasatiht are you sure this was built only from master sources? Or did you use a special EnergyPlus version / download url?
The error message isn’t very explicit so hard to tell what failed.

**Comment by antoine-galataud** [comment]
@Paopasatiht thank you for taking some time to reproduce. 
I believe the problem is because we try to install mpi4py both as a distribution package and a pip package. I’ll test a fix tomorrow but removing `python-mpi4py` package from `apt install` in stage 2 should be enough.
I’ll keep you posted.

**Comment by antoine-galataud** [comment]
@Paopasatiht Hi! I've fixed the `Dockerfile`, would you mind giving it a new try? (don't forget to pull the master branch first)

**Comment by Paopasatiht** [comment]
@antoine-galataud it's finally work now. thankyou so much for your help.
![image](https://user-images.githubusercontent.com/58716875/160663932-c75bc658-953c-4186-9902-0cea7fe081fb.png)

**Comment by antoine-galataud** [comment]
@Paopasatiht great news!
