### ISSUE TITLE
Unable to plot graphs.

### ISSUE THREAD

**Issue by prsi7** [IBM/rl-testbed-for-energyplus#89]
Hi i got Eplog file, but unable get the graphs using - 
python3 -m baselines_energyplus.common.plot_energyplus -l <opengym folder directory >     Please let me know what I'm doing wrong or i need to plot the graph on different platform.

**Comment by prsi7** [comment]
this is the place where i'm stuck now!
![Screenshot from 2022-05-12 18-56-48](https://user-images.githubusercontent.com/82798076/168085871-98d13bda-dc83-47a2-8bd4-4a01935168a9.png)
![Screenshot from 2022-05-12 18-58-12](https://user-images.githubusercontent.com/82798076/168086051-39b7b8ea-7962-49ba-a276-117cb9d61a3b.png)
)

**Comment by antoine-galataud** [comment]
Hi @prsi7. Thanks for reporting this issue. 

The problem comes from an EnergyPlus output variable name change that happened between 9.3.0 and 9.6.0. You can find it mentioned in a documention issue in NREL repo [here](https://github.com/NREL/EnergyPlus/issues/9111#issuecomment-1018766119)

Basically, `Electric Demand Power` variables were renamed `Electricity Demand Rate` in E+ 9.4.0 an onward. The automatic IDF upgrade tool worked well but our python code requires a change.

**Comment by antoine-galataud** [comment]
@prsi7 I've just pushed a fix, let me know if you still face issues with this.

**Comment by prsi7** [comment]
Thank you so much. Yes, it's working now. 

![Screenshot from 2022-05-19 17-16-51](https://user-images.githubusercontent.com/82798076/169289588-3cf4c461-dafd-41cd-a583-aba5b5f10d8c.png)


Also need guidance  regarding the graph plot as per paper like this do we need to plot it separately out side the container  ?  
![energyplus_plot](https://user-images.githubusercontent.com/82798076/169289882-8f73ba9a-0ce1-4e3e-b8c2-8de34bf7a267.png)

**Comment by antoine-galataud** [comment]
please refer to https://github.com/IBM/rl-testbed-for-energyplus/tree/master/docker#plotting (I just added it). Let me know if doesn't work.

**Comment by prsi7** [comment]
@antoine-galataud Thank you so much it is working now with new container. 

What if we want to plot the previous old container which was already trained for so long and has output.

**Comment by antoine-galataud** [comment]
@prsi7 hum, indeed that'd be annoying to lose that. My suggestion:
- run the old container where first experiment ran for a long time
- copy content of experiment folder to your hard drive, with something like 
  ```docker cp [container_name]:/root/eplog/openai-2022-X-Y-Z /tmp/```
- plot using `python3 -m baselines_energyplus.common.plot_energyplus -l /tmp/openai-2022-X-Y-Z` (no need to be in the container for that).
